# Custom theme — just the way I like it.

set -g status on

set -g status-left-length 100
set -g status-right-length 100
set -g status-justify "centre"
set -g status-style "bg=#282c34,fg=#abb2bf"
set -g status-left "#[bg=#61afef,fg=#282c34] u #[bg=#31353f,fg=#abb2bf] #(whoami) #[bg=#61afef,fg=#282c34] p #[bg=#31353f,fg=#abb2bf] #P "
set -g status-right "%a %b %d, %H:%M #[bg=#61afef,fg=#282c34] \uf120 #[bg=#31353f,fg=#abb2bf] #S "

set -g message-style "fg=#abb2bf,bg=#282c34,align=centre"
set -g message-command-style "fg=#abb2bf,bg=#282c34,align=centre"

set -g pane-border-style "fg=#282c34"
set -g pane-active-border-style "fg=#98c379"

setw -g window-status-style "bg=#282c34,fg=#abb2bf,none"
setw -g window-status-separator "#[bg=#282c34,fg=#282c34]|"
setw -g window-status-format "#[bg=#31353f] #I #[default] #(echo '#{pane_current_path}' | rev | cut -d'/' -f-2 | rev) "
setw -g window-status-current-format "#[bg=#61afef,fg=#282c34] #I #[bg=#31353f,fg=#abb2bf] #(echo '#{pane_current_path}' | rev | cut -d'/' -f-2 | rev) "
