#!/usr/bin/env zsh

# file: $ZFUNCDIR/rehash
#
# Optimize Zsh rehashing for pacman cache.
# - Tracks last cache modification time via /var/cache/zsh/pacman.
# - Rehashes commands only when cache is newer than last check.
# - Hooks into precmd to run before each prompt.
#
# See: <https://wiki.archlinux.org/title/Zsh#On-demand_rehash>.

zshcache_time="$(date +%s%N)"

# This line is redundant but harmless (it's idempotent).
autoload -Uz add-zsh-hook

rehash_precmd() {
    if [[ -a /var/cache/zsh/pacman ]]; then
        local paccache_time="$(date -r /var/cache/zsh/pacman +%s%N)"
        if (( zshcache_time < paccache_time )); then
            rehash
            zshcache_time="$paccache_time"
        fi
    fi
}

add-zsh-hook -Uz precmd rehash_precmd
